project:
  type: website
  output-dir: _site

website:
  title: "Kyle Onda"
  description: "Personal website of Kyle Onda"
  site-url: https://kyleonda.com
  repo-url: https://github.com/ksonda/kyleonda.com
#  google-analytics: "G-Y7YLFF5F90"
  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@drewdim"
    site: "@drewdim"
    card-style: "summary_large_image"
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: research.qmd
      - href: software.qmd
      - href: blog.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
