---
title: "About"
---

I am currently an Associate Director of the Center for Geospatial Solutions at the Lincoln Institute of Land Policy, where my primary responsibility is coordinating the development and implementing the technical program of the Internet of Water Coalition.

### Research Interests

-   Causal Inference
-   Machine Learning
-   Data Science
-   Experimental Design

### Education

::: {.d-flex .justify-content-between}
<div>

**University of North Carolina at Chapel Hill**\
PhD in City and Regional Planning\
Advisor: Meenu Tewari

</div>

::: text-end
Chapel Hill, NC\
Expected 2022
:::
:::

-   Dissertation: *Essays on Causal Inference and Machine Learning with Application to Nonprofits*
-   Winner of 2015 Williams Award for Best Dissertation Proposal in Political Methodology from the Society of Political Methodology

::: {.d-flex .justify-content-between}
<div>

**University of North Carolina at Chapel Hill**

-   MCRP in City and Regional Planning

<!-- -->

-   MSPH in Environmental Sciences and Engineering

</div>

::: text-end
Chapel Hill, NC\
Granted June 2014
:::
:::

::: {.d-flex .justify-content-between}
<div>

**Stanford University**

-   BS in Environmental Engineering\
    *Conferred with Distinction*

</div>

::: text-end
Stanford, CA\
Granted June 2011
:::
:::

### Experience

::: {.d-flex .justify-content-between}
<div>

**University of Vienna**

</div>

::: text-end
April 2021 - present
:::
:::

*Scientific Coordinator*

-   Supervisor: Philipp Grohs

::: {.d-flex .justify-content-between}
<div>

**Facebook Core Data Science**

</div>

::: text-end
Sept 2016 - March 2021
:::
:::

*Research Scientist*

-   Part of Eytan Bakshy's Adaptive Experimentation team
-   Developed statistical, machine learning and experimental methodology
-   Ran adaptive and contextual field experiments with a variety of product teams
-   Integrated advanced methodologies into a toolkit for scalable and automatic experimentation intended for optimization ([Ax](https://ax.dev/)) - [released at F8 2019](https://developers.facebook.com/videos/2019/product-optimization-with-adaptive-experimentation/))
-   Developed scalable methods for robust observational causal inference as the technical lead of our "CausalML" initiative

::: {.d-flex .justify-content-between}
<div>

**Princeton University**

</div>

::: text-end
September 2015 - May 2016
:::
:::

*Pre-doctoral fellow*

-   Supervised by Kosuke Imai

::: {.d-flex .justify-content-between}
<div>

**Facebook Core Data Science**

</div>

::: text-end
Summer 2015
:::
:::

*Summer Intern*

-   Statistical and Decision Science Team
-   Supervised by Eytan Bakshy

### Teaching

#### Facebook

::: {.d-flex .justify-content-between}
<div>

Internal datacamp class on designing and analyzing experiments

</div>

::: text-end
2017-2019
:::
:::

#### NYU Undergraduate

::: {.d-flex .justify-content-between}
<div>

TA for Power and Politics in America (under Jonathan Nagler)

</div>

::: text-end
Fall 2014
:::
:::

::: {.d-flex .justify-content-between}
<div>

TA for Games, Strategy and Politics (under Steven Brams)

</div>

::: text-end
Fall 2013
:::
:::

#### NYU Graduate

::: {.d-flex .justify-content-between}
<div>

TA for Quantitative Methods II (under Nathaniel Beck)

</div>

::: text-end
Spring 2015
:::
:::

::: {.d-flex .justify-content-between}
<div>

TA for Quantitative Methods II (under Cyrus Samii)

</div>

::: text-end
Spring 2014
:::
:::

::: {.d-flex .justify-content-between}
<div>

High Performance Computing Talk for NYU Datalab

</div>

::: text-end
February 2014
:::
:::

::: {.d-flex .justify-content-between}
<div>

Introduction to R for NYU Datalab

</div>

::: text-end
January 2013
:::
:::
